matrix:
    include:
        - name: "Linux pytest"
          services:
            - docker
          language: minimal
          env: BUILD_WHEEL=true
        - name: "Linux ctest"
          services:
            - docker
          language: minimal
          env: BUILD_WHEEL=false
        - name: "Linux clang-tidy"
          services:
            - docker
          language: minimal
          env: USE_CLANG_TIDY
        - name: "macOS py3.6"
          os: osx
          language: shell
          osx_image: xcode10.1
          env: PYTHON=3.6
          addons:
              homebrew:
                packages:
                - gcc@8
                - verilator


script:
    - ./scripts/ci.sh

deploy:
  - provider: script
    script: /bin/bash scripts/deploy.sh
    on:
      branch: master
      tags: true
